>[Inner product Matrix - Vector](#scrollTo=1se0A7uO27dx)

>[Inner product Matrix - Matrix](#scrollTo=bKiQD_bF381p)

>[Transpose and Inner product](#scrollTo=tj49SYra7DS_)

>[Check the solution of a linear equation system](#scrollTo=6pPWmKiP78mM)

>[Inverse matrix: Solve linear equation systems](#scrollTo=fSzNcz4Iy0Wr)



# Inner product Matrix - Vector

Recall that the inner product between 2 vectors returns a scalar meanwhile the outer product returns a matrix.

The inner product is also Known as the usual matrix product. But linear algebra allows many other product types.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
vector = np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

In [ ]:
matrix = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
matrix

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
A = matrix*vector
A

array([[ 1,  4,  9, 16, 25],
       [ 1,  4,  9, 16, 25],
       [ 1,  4,  9, 16, 25]])

In [ ]:
B = matrix.dot(vector)
B

array([55, 55, 55])

# Inner product Matrix - Matrix
For two matrices to have an inner product, the number of columns in the first must be equal to the number of rows in the second.

Subsequently, perform an internal product between the row vectors of the first matrix with the column vectors of the second matrix, generating a new matrix that will have the dimensions of the number of rows of the first matrix and the number of columns of the second matrix.

Let $A_{n,m}, B_{s,t}$ be two matrices, the inner product between $A$ and $B$ is defined **if and only if** $m=s$.

Some properties of the inner product are:

- Asociativity.
- Distributivity of $+$ with respect to $\cdot$.
- No conmutativity.

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
B = np.array([[2,3], [5,7], [11,13]])

In [ ]:
C = A.dot(B)
C

array([[ 45,  56],
       [ 99, 125],
       [153, 194],
       [207, 263]])

In [ ]:
D = B.dot(A)

ValueError: ignored

This error occurs cuz the number columns of $B (2)$ doesn't coincide with the number of rows of $A (4)$

# Transpose and Inner product

We have the following properties for matrices $A$ and $B$ that are inner-multiplicable:

- $(AB)^T=B^TA^T$
- $(A^T)^T = A$

In [ ]:
(A.dot(B)).T == B.T.dot(A.T)

In [ ]:
(A.T).T == A

# Check the solution of a linear equation system

In [ ]:
x = np.arange(-5, 5, 0.1)
y_1 = 3*x+5
y_2 = 2*x+3

In [ ]:
plt.figure(figsize = (8, 8))

plt.plot(x, y_1)
plt.plot(x, y_2)

plt.xlim(-5, 5)
plt.ylim(-20, 20)

plt.axvline(x=0, color='gray')
plt.axhline(y=0, color='gray')

In [ ]:
A = np.array([[-3,1], [-2,1]])
A

In [ ]:
b = np.array([5, 3])
b

In [ ]:
sol_1 = np.array([-2, -1])
sol_1

In [ ]:
A.dot(sol_1) == b

# Inverse matrix: Solve linear equation systems

Observe that, if a matrix $A$ is invertible, then, the solution of the system $$Ax=b$$ has unique solution $$x=A^{-1}b$$

In [ ]:
#Round approximations
np.set_printoptions(suppress=True)

In [ ]:
A = np.array([[3,1],[2,1]])
A

array([[3, 1],
       [2, 1]])

In [ ]:
b = np.array([1,1])

In [ ]:
inverse_A = np.linalg.inv(A)
inverse_A

array([[ 1., -1.],
       [-2.,  3.]])

In [ ]:
x = inverse_A.dot(b)
x

array([0., 1.])

In [ ]:
# Check
A.dot(x) == b

array([ True,  True])

---
*Let’s change the world, Together!*


<img align=centerright src="https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F202df933-5432-47f6-aba6-a9a054cece4b%2Fpages-PhotoRoom.png?table=block&id=0b1ffffe-7be4-41f2-86dd-26cad410a64b&spaceId=12eea25e-0790-4a8f-aa1c-b60f93c02da2&width=250&userId=4be5c684-7292-494e-bbb2-2554f1af3879&cache=v2"  width="70" height="70">

<img align=centerright src="https://cdn-icons-png.flaticon.com/512/25/25231.png"  width="70" height="70">
<img align=centerright src="https://cdn-icons-png.flaticon.com/512/61/61109.png?w=360"  width="70" height="70">
<img align=centerright src="https://cdn-icons-png.flaticon.com/512/39/39552.png"  width="70" height="70">
<img align=centerright src="https://cdn.freebiesupply.com/images/large/2x/instagram-icon-white-on-black.png"  width="100" height="70">

[Personal Blog](https://santiagoal.super.site/)      [GitHub](https://github.com/santiagoahl)    [LinkedIn](https://www.linkedin.com/in/santiago-ahumada-lozano/)   [Twitter](https://twitter.com/sahumadaloz)  [Instagram](https://www.instagram.com/santiago_al10/)
